# clio completion for fish — generated by 'clio completions fish'

# Print an optspec for argparse to handle cmd's options that are independent of any subcommand.
function __fish_clio_global_optspecs
	string join \n i/index= h/help V/version
end

function __fish_clio_needs_command
	# Figure out if the current invocation already has a command.
	set -l cmd (commandline -opc)
	set -e cmd[1]
	argparse -s (__fish_clio_global_optspecs) -- $cmd 2>/dev/null
	or return
	if set -q argv[1]
		# Also print the command, so this can be used to figure out what it is.
		echo $argv[1]
		return 1
	end
	return 0
end

function __fish_clio_using_subcommand
	set -l cmd (__fish_clio_needs_command)
	test -z "$cmd"
	and return 1
	contains -- $cmd[1] $argv
end

complete -c clio -n "__fish_clio_needs_command" -s i -l index -d 'Get value by its 0-based list index (uses default db, forward order). Use after `clio list` to identify the desired key' -r
complete -c clio -n "__fish_clio_needs_command" -s h -l help -d 'Print help'
complete -c clio -n "__fish_clio_needs_command" -s V -l version -d 'Print version'
complete -c clio -n "__fish_clio_needs_command" -f -a "set" -d 'Set a value for a key with an optional @db. If VALUE is omitted, reads from stdin'
complete -c clio -n "__fish_clio_needs_command" -f -a "put" -d 'Set a value for a key with an optional @db. If VALUE is omitted, reads from stdin'
complete -c clio -n "__fish_clio_needs_command" -f -a "get" -d 'Get a value for a key with an optional @db'
complete -c clio -n "__fish_clio_needs_command" -f -a "delete" -d 'Delete a key with an optional @db'
complete -c clio -n "__fish_clio_needs_command" -f -a "del" -d 'Delete a key with an optional @db'
complete -c clio -n "__fish_clio_needs_command" -f -a "rm" -d 'Delete a key with an optional @db'
complete -c clio -n "__fish_clio_needs_command" -f -a "list" -d 'List key-value pairs with an optional @db'
complete -c clio -n "__fish_clio_needs_command" -f -a "ls" -d 'List key-value pairs with an optional @db'
complete -c clio -n "__fish_clio_needs_command" -f -a "list-dbs" -d 'List all databases'
complete -c clio -n "__fish_clio_needs_command" -f -a "ls-db" -d 'List all databases'
complete -c clio -n "__fish_clio_needs_command" -f -a "delete-db" -d 'Delete a database and all its contents'
complete -c clio -n "__fish_clio_needs_command" -f -a "del-db" -d 'Delete a database and all its contents'
complete -c clio -n "__fish_clio_needs_command" -f -a "rm-db" -d 'Delete a database and all its contents'
complete -c clio -n "__fish_clio_needs_command" -f -a "push" -d 'Push a local database to S3'
complete -c clio -n "__fish_clio_needs_command" -f -a "pull" -d 'Pull a database from S3, overwriting local'
complete -c clio -n "__fish_clio_needs_command" -f -a "sync" -d 'Bidirectional sync: push local changes, pull remote changes'
complete -c clio -n "__fish_clio_needs_command" -f -a "sync-status" -d 'Show sync status (local vs remote diff)'
complete -c clio -n "__fish_clio_needs_command" -f -a "init-config" -d 'Create a config file template at ~/.config/clio/config.toml'
complete -c clio -n "__fish_clio_needs_command" -f -a "completions" -d 'Generate shell completion script (bash, zsh, fish)'
complete -c clio -n "__fish_clio_needs_command" -f -a "complete" -d 'Dynamic completion engine for keys and database names (used by shell scripts)'
complete -c clio -n "__fish_clio_needs_command" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c clio -n "__fish_clio_using_subcommand set" -s h -l help -d 'Print help'
complete -c clio -n "__fish_clio_using_subcommand put" -s h -l help -d 'Print help'
complete -c clio -n "__fish_clio_using_subcommand get" -s b -l show-binary -d 'Show binary values instead of omitting them'
complete -c clio -n "__fish_clio_using_subcommand get" -s h -l help -d 'Print help'
complete -c clio -n "__fish_clio_using_subcommand delete" -s h -l help -d 'Print help'
complete -c clio -n "__fish_clio_using_subcommand del" -s h -l help -d 'Print help'
complete -c clio -n "__fish_clio_using_subcommand rm" -s h -l help -d 'Print help'
complete -c clio -n "__fish_clio_using_subcommand list" -s d -l delimiter -d 'Delimiter between keys and values (default: tab)' -r
complete -c clio -n "__fish_clio_using_subcommand list" -s w -l max-value-width -d 'Max displayed value width in terminal (0 = no truncation, default: 8). When a value exceeds this length, it is cut to `width` chars and suffixed with "...".  Piped output is never truncated' -r
complete -c clio -n "__fish_clio_using_subcommand list" -s r -l reverse -d 'List in reverse lexicographic order'
complete -c clio -n "__fish_clio_using_subcommand list" -s k -l keys-only -d 'Only print keys (skip fetching values)'
complete -c clio -n "__fish_clio_using_subcommand list" -s v -l values-only -d 'Only print values'
complete -c clio -n "__fish_clio_using_subcommand list" -s b -l show-binary -d 'Show binary values instead of omitting them'
complete -c clio -n "__fish_clio_using_subcommand list" -s h -l help -d 'Print help'
complete -c clio -n "__fish_clio_using_subcommand ls" -s d -l delimiter -d 'Delimiter between keys and values (default: tab)' -r
complete -c clio -n "__fish_clio_using_subcommand ls" -s w -l max-value-width -d 'Max displayed value width in terminal (0 = no truncation, default: 8). When a value exceeds this length, it is cut to `width` chars and suffixed with "...".  Piped output is never truncated' -r
complete -c clio -n "__fish_clio_using_subcommand ls" -s r -l reverse -d 'List in reverse lexicographic order'
complete -c clio -n "__fish_clio_using_subcommand ls" -s k -l keys-only -d 'Only print keys (skip fetching values)'
complete -c clio -n "__fish_clio_using_subcommand ls" -s v -l values-only -d 'Only print values'
complete -c clio -n "__fish_clio_using_subcommand ls" -s b -l show-binary -d 'Show binary values instead of omitting them'
complete -c clio -n "__fish_clio_using_subcommand ls" -s h -l help -d 'Print help'
complete -c clio -n "__fish_clio_using_subcommand list-dbs" -s h -l help -d 'Print help'
complete -c clio -n "__fish_clio_using_subcommand ls-db" -s h -l help -d 'Print help'
complete -c clio -n "__fish_clio_using_subcommand delete-db" -s h -l help -d 'Print help'
complete -c clio -n "__fish_clio_using_subcommand del-db" -s h -l help -d 'Print help'
complete -c clio -n "__fish_clio_using_subcommand rm-db" -s h -l help -d 'Print help'
complete -c clio -n "__fish_clio_using_subcommand push" -l force -d 'Force push even if remote has changed'
complete -c clio -n "__fish_clio_using_subcommand push" -s h -l help -d 'Print help'
complete -c clio -n "__fish_clio_using_subcommand pull" -l force -d 'Force pull even if local has unsynced changes'
complete -c clio -n "__fish_clio_using_subcommand pull" -s h -l help -d 'Print help'
complete -c clio -n "__fish_clio_using_subcommand sync" -l force -d 'Force resolution direction when databases have diverged' -r -f -a "push\t''
pull\t''"
complete -c clio -n "__fish_clio_using_subcommand sync" -s h -l help -d 'Print help'
complete -c clio -n "__fish_clio_using_subcommand sync-status" -s h -l help -d 'Print help'
complete -c clio -n "__fish_clio_using_subcommand init-config" -s h -l help -d 'Print help'
complete -c clio -n "__fish_clio_using_subcommand completions" -s h -l help -d 'Print help'
complete -c clio -n "__fish_clio_using_subcommand complete" -s d -l db -d 'Database to query (defaults to "default"; ignored with --dbs)' -r
complete -c clio -n "__fish_clio_using_subcommand complete" -s D -l dbs -d 'Complete database names instead of keys'
complete -c clio -n "__fish_clio_using_subcommand complete" -s h -l help -d 'Print help'
complete -c clio -n "__fish_clio_using_subcommand help; and not __fish_seen_subcommand_from set get delete list list-dbs delete-db push pull sync sync-status init-config completions complete help" -f -a "set" -d 'Set a value for a key with an optional @db. If VALUE is omitted, reads from stdin'
complete -c clio -n "__fish_clio_using_subcommand help; and not __fish_seen_subcommand_from set get delete list list-dbs delete-db push pull sync sync-status init-config completions complete help" -f -a "get" -d 'Get a value for a key with an optional @db'
complete -c clio -n "__fish_clio_using_subcommand help; and not __fish_seen_subcommand_from set get delete list list-dbs delete-db push pull sync sync-status init-config completions complete help" -f -a "delete" -d 'Delete a key with an optional @db'
complete -c clio -n "__fish_clio_using_subcommand help; and not __fish_seen_subcommand_from set get delete list list-dbs delete-db push pull sync sync-status init-config completions complete help" -f -a "list" -d 'List key-value pairs with an optional @db'
complete -c clio -n "__fish_clio_using_subcommand help; and not __fish_seen_subcommand_from set get delete list list-dbs delete-db push pull sync sync-status init-config completions complete help" -f -a "list-dbs" -d 'List all databases'
complete -c clio -n "__fish_clio_using_subcommand help; and not __fish_seen_subcommand_from set get delete list list-dbs delete-db push pull sync sync-status init-config completions complete help" -f -a "delete-db" -d 'Delete a database and all its contents'
complete -c clio -n "__fish_clio_using_subcommand help; and not __fish_seen_subcommand_from set get delete list list-dbs delete-db push pull sync sync-status init-config completions complete help" -f -a "push" -d 'Push a local database to S3'
complete -c clio -n "__fish_clio_using_subcommand help; and not __fish_seen_subcommand_from set get delete list list-dbs delete-db push pull sync sync-status init-config completions complete help" -f -a "pull" -d 'Pull a database from S3, overwriting local'
complete -c clio -n "__fish_clio_using_subcommand help; and not __fish_seen_subcommand_from set get delete list list-dbs delete-db push pull sync sync-status init-config completions complete help" -f -a "sync" -d 'Bidirectional sync: push local changes, pull remote changes'
complete -c clio -n "__fish_clio_using_subcommand help; and not __fish_seen_subcommand_from set get delete list list-dbs delete-db push pull sync sync-status init-config completions complete help" -f -a "sync-status" -d 'Show sync status (local vs remote diff)'
complete -c clio -n "__fish_clio_using_subcommand help; and not __fish_seen_subcommand_from set get delete list list-dbs delete-db push pull sync sync-status init-config completions complete help" -f -a "init-config" -d 'Create a config file template at ~/.config/clio/config.toml'
complete -c clio -n "__fish_clio_using_subcommand help; and not __fish_seen_subcommand_from set get delete list list-dbs delete-db push pull sync sync-status init-config completions complete help" -f -a "completions" -d 'Generate shell completion script (bash, zsh, fish)'
complete -c clio -n "__fish_clio_using_subcommand help; and not __fish_seen_subcommand_from set get delete list list-dbs delete-db push pull sync sync-status init-config completions complete help" -f -a "complete" -d 'Dynamic completion engine for keys and database names (used by shell scripts)'
complete -c clio -n "__fish_clio_using_subcommand help; and not __fish_seen_subcommand_from set get delete list list-dbs delete-db push pull sync sync-status init-config completions complete help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'

# Dynamic key completion
complete -c clio -n "__fish_seen_subcommand_from get set put delete del rm" \
    -a "(clio complete (commandline -ct) 2>/dev/null)"

# Dynamic db completion
complete -c clio -n "__fish_seen_subcommand_from delete-db del-db rm-db push pull list ls" \
    -a "(clio complete --dbs (commandline -ct) 2>/dev/null)"
